spring.application.name=zoopzoop
server.port=8080
spring.datasource.url=jdbc:postgresql://localhost:5432/ZoopZoop_DB
spring.datasource.username=postgres
spring.datasource.password=sjs5382352
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=zoopzoop-secret-key-should-be-long-enough-2026
jwt.access-token-expiration-seconds=86400

# OPEN API KEY
gov.api.key=dcf39234340da7c33c551ad4498ccc496b5f6e153d9d2987ea8665493eacca18
