# [? ?? Supabase DB ?? ??]
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.zzhmvoudkavrywmepqqp
spring.datasource.password=sjs5382352+++

# ???? DB? ??? ??? ? ??? 'validate'? ?????.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver