# [?? ?? DB ?? ??]
spring.datasource.url=jdbc:postgresql://localhost:5432/ZoopZoop_DB
spring.datasource.username=postgres
spring.datasource.password=sjs5382352

# ????? ???? ???? ??/???? ?????.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true