# --- [? ????? ???? DB ??] ---

# 1. URL (??? 6543?? ???? ?? IPv4 ???? ?? ?????)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:5432/postgres

# 2. ??? ?? (? ???? ID ??)
spring.datasource.username=postgres.zzhmvoudkavrywmepqqp

# 3. ???? (? ???? ????)
spring.datasource.password=${SUPABASE_DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=0
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
