# --- [? ????? ???? DB ??] ---

# 1. URL (??? 6543?? ???? ?? IPv4 ???? ?? ?????)
spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres

# 2. ??? ?? (? ???? ID ??)
spring.datasource.username=postgres.zzhmvoudkavrywmepqqp

# 3. ???? (? ???? ????)
spring.datasource.password=sjs5382352+++

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
